### ISSUE TITLE
Сделать логику для вывода приглашения PS2

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#26]
Когда вводим незавершенный subshell или brace_group, ожидаем увидеть:
```
PiEcE_oF_s_HELL: asdf(
8===D: ...
```
Имеем:
```
PiEcE_oF_s_HELL: asdf(
PiEcE_oF_s_HELL: ...
```

**Comment by ag95v2** [comment]
Сюда же относится незавершенная команда
ls |
cat | 
...
