### ISSUE TITLE
Для 22 теста выводится сообщение об ошибке, когда закрывается stderr

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#32]
```
rm nosuchfile 2>&-
```
expected test_err_checkilst_22: ""
was user_err_checkilst_22: rm: nosuchfile: No such file or directory

**Comment by ag95v2** [comment]
Fixed
https://github.com/Tsorion9/42sh/commit/e29536fdabbee3eabfbd6d5c9f99f8e6ae1c10ef
