### ISSUE TITLE
Для exp_varname_quote заресерчить ошибку

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#33]
```
echo hello >'~/a'
rm -f '~/a'
```
PiEcE_oF_s_HELL: echo hello >"~/a"
Could not open file: ~/a
hello
PiEcE_oF_s_HELL: echo hello >'~/a'
Could not open file: ~/a
hello
Предположу, что надо доработать, чтобы не исполнять команду при ошибке открытия файла

**Comment by ag95v2** [comment]
Fixed
https://github.com/Tsorion9/42sh/commit/0546ffa33b3764a0fb2869eb67110c4f962cce07

С ресерчем ошибки пока не продвинулся, очень интересная ошибка))
