### ISSUE TITLE
[CD] Don't work variable monitoring

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#37]
```
HOME=/tmp
cd
pwd
```
ОР(Ожидаемый результат): /tmp
ФР(Фактический результат): 42sh: cd: HOME not set (or set to NULL)

**Comment by ag95v2** [comment]
Fixed
https://github.com/Tsorion9/42sh/commit/b85b750c2e21e91c2d4c2cfeb260ffa245531ef7
