### ISSUE TITLE
[BUILTIN][PWD][Доделать обработку аргументов для pwd]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#48]
```
pwd cd -
```
ОР: *print current directory*
ФР: usage: pwd [-L | -P]
Предполагаемое решение:
1) Если первый аргумент не флаг, предполагаем, что флагов нет
2) Если первый аргумент флаг, проверяем, что он один из [-L | -P], если нет вывести ошибку usage: pwd [-L | -P]
3) Если флаг валидный, то считывать флаги пока они валидны

**Comment by volkov7** [comment]
Тест: 42_checklist15.txt

**Comment by ag95v2** [comment]
Нам не нужен такой builtin.

**Comment by volkov7** [comment]
А, я думал, pwd это билтын)) Тогда предлагаю удалить этот билтын

**Comment by ag95v2** [comment]
bash использовал builtin pwd вместо /bin/pwd. 
Fixed
