### ISSUE TITLE
[TEST][CHECKLIST-17][Тест падает из-за модификации во время исполнения]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#49]
В логах вывода bash:
```
-rw-r--r--    1 volkker  staff      ->9<- Feb 12 18:56 last_valgrind_output
drwxr-xr-x  ->216< volkker  staff   ->6912<- Feb 12 18:56 output
```
В логах вывода 42sh:
```
-rw-r--r--    1 volkker  staff      ->2<- Feb 12 18:56 last_valgrind_output
drwxr-xr-x  ->215<- volkker  staff   ->6880<- Feb 12 18:56 output
```

Предполагаема проблема: во время исполнения тестов изменяется размер фалов, что влияет на вывод команды ls, из-за этого сравнение показывает  FAIL.

**Comment by volkov7** [comment]
К этому же issue новый тест inhibitors падает по той же причине

**Comment by ag95v2** [comment]
https://github.com/Tsorion9/42sh/commit/7b42cf678f79ffb1ecf53c02c3b30fad9b7f6313
