### ISSUE TITLE
[TESTS][42CHECKLIST-21][Не выводится сообщение в stderr]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#52]
```
python3  -c "import os, signal;os.kill(os.getpid(), signal.SIGSEGV)"; echo $?
```
ОР: /bin/bash: line 2: 20679 Segmentation fault: 11  python3 -c "import os, signal;os.kill(os.getpid(), signal.SIGSEGV)"
ФР:""

**Comment by ag95v2** [comment]
Поменял тест
