### ISSUE TITLE
[BUILTIN][CD][Возвращает непонятный статус]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#57]
```
PiEcE_oF_s_HELL: cd /
PiEcE_oF_s_HELL: echo $?
129
PiEcE_oF_s_HELL: 
```
ОР: 0
ФР: 129

**Comment by volkov7** [comment]
Для builtin ```set/unset``` наблюдается аналогичная проблема

**Comment by ag95v2** [comment]
https://github.com/Tsorion9/42sh/commit/9d62c08b8b5ed415052c4a293432aa4804836318
