### ISSUE TITLE
$(ww[enter]ee[enter]qq)

### ISSUE THREAD

**Issue by Tsorion9** [Tsorion9/42sh#59]
При вводе многострочной команды происходит ошибка.
### Команда:
**$(ww
ee
qq)**

### ОР: 
**42sh: ww: command not found
42sh: ee: command not found
42sh: qq: command not found**

### ФР:
**ww:: command not found
free(): double free detected in tcache 2
Aborted**

**Comment by volkov7** [comment]
commit d6e42d848901acbc7cf295f67c56f56be1ab900c
