### ISSUE TITLE
[ALIAS] Мы применяем поиск по алиасам к первому токену в команде, а надо - к первому слову

### ISSUE THREAD

**Issue by ag95v2** [Tsorion9/42sh#75]
Expected:
w@q:~/42sh$ alias a=b
w@q:~/42sh$ c=d a
b: command not found
w@q:~/42sh$ 2>&1 a
b: command not found

Got:
PiEcE_oF_s_HELL: alias a=b
PiEcE_oF_s_HELL: c=d a
42sh: a: command not found
PiEcE_oF_s_HELL: 2>&1 a
42sh: a: command not found

Wontfix?

**Comment by volkov7** [comment]
Думаю, для нашей архитектуры будет ~~сложно~~ муторно поддержать этот кейс.
