### ISSUE TITLE
[SIGNALS][CHECKLIST][Не выводим сообщение об сигинте]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#81]
```
PiEcE_oF_s_HELL: python -c 'import os, signal;os.kill(os.getpid(), signal.SIGSEGV)'
```
ОР: Segmentation fault: 11
ФР: ""

**Comment by ag95v2** [comment]
Такое поведение по стандарту является результатом наличия set -m
Мы не поддерживаем флаги set, выбираем стратегию не выводить лишнего.
Информация о статусе завершения дочернего процесса не теряется.
