### ISSUE TITLE
[CHECKLIST][PATTERN MATCHING]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#82]
```
PiEcE_oF_s_HELL: touch ".bc" "abc" "bbc" "cbc" "-bc" '!bc' "+bc" ",bc" "0bc" "1bc"
PiEcE_oF_s_HELL: echo [!-ab]*
```
ОР: !bc +bc ,bc 0bc 1bc cbc
ФР: [abc $ $]*

```
PiEcE_oF_s_HELL: echo [!ab]*
```
ОР: !bc +bc ,bc -bc 0bc 1bc cbc
ФР: [abc $]*

```
PiEcE_oF_s_HELL: echo []ab]*
```
ОР: abc bbc
ФР: []ab]*

```
PiEcE_oF_s_HELL: echo [z-a]*
```
ОР: [z-a]*
ФР: abc bbc abc

Возможная причина проблемы: восклицательные знаки рассматриваются, как history expansion

**Comment by ag95v2** [comment]
1) Вместо ! мы используем ^.
2) range [a-z] и [z-a], кажется, у нас можно задавать в любом порядке
Остальные моменты пока под вопросом. 
[]ab]* - кажется, заведомо не соответствующий ни одному имени файла паттерн (начинается с пустого множества символов)

**Comment by volkov7** [comment]
А мы разве z-a не фиксили?

**Comment by ag95v2** [comment]
Не фиксили. Это сделать можно, но, на мой взгляд, не нужно.
Удобно задавать последовательности в произвольном порядке.
[]ab]* - тоже логичное поведение, предлагаю забить на чеклист.

**Comment by volkov7** [comment]
Поддерживаю
