### ISSUE TITLE
[BUILTIN CD][BEHAVIOUR]

### ISSUE THREAD

**Issue by volkov7** [Tsorion9/42sh#83]
```
$> unset HOME && cd / && cd ~; pwd
{{ Print an error message }}
```
ФР: {{ Print user home path }}

у нас поведение, как и у баша, но в чеклисте просят выводить ошибку в таком случае.

**Comment by ag95v2** [comment]
Что касается cd
1) If no directory operand is given and the HOME environment variable is empty or undefined, the default behavior is implementation-defined and no further steps shall be taken.

Но в примере ~ заменилась на домашнюю директорию текущего пользователя, что по стандарту на наше усмотрение
2) f the login name is null (that is, the tilde-prefix contains only the tilde), the tilde-prefix is replaced by the value of the variable HOME. If HOME is unset, the results are unspecified.
